### ISSUE TITLE
Error in latest version

### ISSUE THREAD

**Issue by owenselles** [alfianlosari/ChatGPTSwift#10]
Failed to resolve dependencies Dependencies could not be resolved because 'gptencoder' 1.0.0 contains incompatible tools version (5.8.0) and 'chatgptswift' depends on 'gptencoder' 1.0.0.

**Comment by alfianlosari** [comment]
Thanks for reporting, looking into it

**Comment by alfianlosari** [comment]
I have fixed this issue in 1.3.2 https://github.com/alfianlosari/ChatGPTSwift/releases/tag/1.3.2
