### ISSUE TITLE
Add finished callback in sendMessageStream

### ISSUE THREAD

**Issue by roimulia2** [alfianlosari/ChatGPTSwift#15]
Hey! Thank you for this amazing repository. 

We are trying to handle a situation where we don't let the user send another message while the chat is responding to the user's input. Currently, as far as we can tell, there is no way to detect when the message stopped streaming (tho I do see something like): `                    continuation.finish()
`
But it's not exposed. Thank you!

**Comment by alfianlosari** [comment]
thanks for replying with clear explanation @DimonDeveloper . 

@roimulia2 you can check the sample app https://github.com/alfianlosari/ChatGPTSwiftUI for similar use case.

closing this thread
