### ISSUE TITLE
Ability to add history

### ISSUE THREAD

**Issue by csamzhou** [alfianlosari/ChatGPTSwift#3]
Hi, thanks for the good work.

Just wondering can you add the ability to add the history back to the api?

**Comment by alfianlosari** [comment]
Nice idea, i can create a public method that accepts array of Message list, and append it to the internal history list.

**Comment by alfianlosari** [comment]
Hi, i have published 1.2.1 version containing replace history list public method https://github.com/alfianlosari/ChatGPTSwift/releases/tag/1.2.1

**Comment by csamzhou** [comment]
Thanks!
