### ISSUE TITLE
History won't get truncated

### ISSUE THREAD

**Issue by dchest** [alfianlosari/ChatGPTSwift#7]
Here https://github.com/alfianlosari/ChatGPTSwift/blob/main/Sources/ChatGPTSwift/ChatGPTAPI.swift#L58:

`_ = historyList.dropFirst()` just returns a new sequence without the first element and doesn't change `historyList` itself. Instead, you can use `historyList.removeFirst()`.

PS Thanks for the package!

**Comment by alfianlosari** [comment]
Hey thanks for pointing out, will fix this!

**Comment by alfianlosari** [comment]
I have fixed this in 1.3.1 https://github.com/alfianlosari/ChatGPTSwift/releases/tag/1.3.1
